//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_ClientVehicles
    {
        public int Audit_ClientVehicles_Id { get; set; }
        public int ClientVehicleId { get; set; }
        public int ClientId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public string PlateState { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<System.DateTime> RegistrationExpiration { get; set; }
        public string InsuranceCarrier { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceExpiration { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
