//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_ClientSessionNotes
    {
        public int Audit_ClientSessionNoteId { get; set; }
        public int ClientSessionNoteId { get; set; }
        public int ClientGroupRegistrationId { get; set; }
        public string TreatmentGroup { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public int SessionLength { get; set; }
        public string Facilitator { get; set; }
        public string Attendance { get; set; }
        public string BAResult { get; set; }
        public Nullable<int> WeeklySelfHelps { get; set; }
        public string Behavior { get; set; }
        public string Assessment { get; set; }
        public string PlanText { get; set; }
        public string Curriculum { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Progress { get; set; }
    }
}
