//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_ClientTreatmentPlans
    {
        public int Audit_ClientTreatmentPlanId { get; set; }
        public int ClientTreatmentPlanId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public string TreatmentPlanName { get; set; }
        public System.DateTime TreatmentPlanDate { get; set; }
        public string ResidentProfile { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string AdditionalSignerDescription { get; set; }
        public string AdditionalSignerDescription2 { get; set; }
        public string ClientSigned { get; set; }
        public string StaffSigned { get; set; }
        public string AdditionalSigner1 { get; set; }
        public string AdditionalSigner2 { get; set; }
    }
}
