//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_ClientProgramEnrollments
    {
        public int Audit_ClientProgramEnrollments_Id { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int ClientId { get; set; }
        public string Program { get; set; }
        public string ClientIdentifier { get; set; }
        public string ClientScreening { get; set; }
        public string ManagingLocation { get; set; }
        public string ReferralSource { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public string CaseManager { get; set; }
        public string SecondaryCaseManager { get; set; }
        public Nullable<System.DateTime> ScheduledArrivalDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> HomeConfinementEligibleDate { get; set; }
        public Nullable<System.DateTime> TransitionalLivingDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string TerminationReason { get; set; }
        public string ReleaseTo { get; set; }
        public string SecondaryRelease { get; set; }
        public string DNARequired { get; set; }
        public string LabAccountNumber { get; set; }
        public string Billing { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<decimal> RecurringFee { get; set; }
        public Nullable<decimal> ProjectedFees { get; set; }
    }
}
