//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRegister
    {
        public int CheckRegisterId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ClientResidentFinancialAccountDetailId { get; set; }
        public Nullable<int> CompanyFinancialsId { get; set; }
        public int CheckNumber { get; set; }
        public System.DateTime CheckDate { get; set; }
        public decimal CheckAmount { get; set; }
        public string Payee { get; set; }
        public string AdditionalPayeeInfo { get; set; }
        public string CheckMemo { get; set; }
        public Nullable<int> CompanyFinancialAccountId { get; set; }
        public string Reprinted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientResidentFinancialAccountDetail ClientResidentFinancialAccountDetail { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyFinancialAccount CompanyFinancialAccount { get; set; }
        public virtual CompanyFinancial CompanyFinancial { get; set; }
    }
}
