//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDocket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientDocket()
        {
            this.ClientOffenses = new HashSet<ClientOffens>();
            this.ClientProgramEnrollmentDockets = new HashSet<ClientProgramEnrollmentDocket>();
        }
    
        public int ClientDocketId { get; set; }
        public int ClientId { get; set; }
        public string DocketNumber { get; set; }
        public Nullable<int> Court { get; set; }
        public string Attorney { get; set; }
        public string Judge { get; set; }
        public Nullable<int> County { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> SentencedTo { get; set; }
        public string SentenceDescription { get; set; }
        public Nullable<int> TotalSentenceDays { get; set; }
        public Nullable<int> WorkReleaseDays { get; set; }
        public Nullable<int> DetentionDays { get; set; }
        public Nullable<int> HouseArrestDays { get; set; }
        public Nullable<int> MonitoringDays { get; set; }
        public Nullable<int> SupervisionDays { get; set; }
        public Nullable<int> CommunityServiceHours { get; set; }
        public Nullable<int> CreditedJailDays { get; set; }
        public Nullable<System.DateTime> DateSentenced { get; set; }
        public Nullable<System.DateTime> Discharge { get; set; }
        public Nullable<System.DateTime> DischargeToSS { get; set; }
        public Nullable<System.DateTime> DateReceivedAtPrision { get; set; }
        public Nullable<System.DateTime> DateSentenceCommenced { get; set; }
        public Nullable<decimal> RestitutionAmount { get; set; }
        public string ProbationOfficer { get; set; }
        public string ProbationOfficerPhone { get; set; }
        public string VictimName { get; set; }
        public string VictimAddress { get; set; }
        public string SpecialConditions { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOffens> ClientOffenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollmentDocket> ClientProgramEnrollmentDockets { get; set; }
    }
}
