//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOffens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientOffens()
        {
            this.ClientScreeningOffenses = new HashSet<ClientScreeningOffens>();
        }
    
        public int ClientOffenseId { get; set; }
        public int ClientId { get; set; }
        public int Offense { get; set; }
        public Nullable<System.DateTime> OffenseDate { get; set; }
        public Nullable<int> DocketId { get; set; }
        public string RevocationStatus { get; set; }
        public string Details { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string PrimaryOffense { get; set; }
    
        public virtual ClientDocket ClientDocket { get; set; }
        public virtual Client Client { get; set; }
        public virtual Offens Offens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningOffens> ClientScreeningOffenses { get; set; }
    }
}
