//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOTCMedicationLog
    {
        public int ClientOTCMedicationLogId { get; set; }
        public int ClientId { get; set; }
        public int OTCMedicationId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int LogType { get; set; }
        public decimal Quantity { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public byte[] ClientSignature { get; set; }
        public byte[] StaffSignature { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual User User { get; set; }
    }
}
