//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScreening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientScreening()
        {
            this.ClientProgramEnrollments = new HashSet<ClientProgramEnrollment>();
            this.ClientScreeningApprovalConditions = new HashSet<ClientScreeningApprovalCondition>();
            this.ClientScreeningMedications = new HashSet<ClientScreeningMedication>();
            this.ClientScreeningOffenses = new HashSet<ClientScreeningOffens>();
            this.ClientScreeningPreviousDenials = new HashSet<ClientScreeningPreviousDenial>();
            this.ClientScreeningPrograms = new HashSet<ClientScreeningProgram>();
            this.ClientScreeningPsychConditions = new HashSet<ClientScreeningPsychCondition>();
        }
    
        public int ClientScreeningId { get; set; }
        public int ClientId { get; set; }
        public int ClientIdentifierId { get; set; }
        public System.DateTime ScreeningFileReceivedDate { get; set; }
        public Nullable<int> ReferralSourceId { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string ParoleOfficer { get; set; }
        public string ParoleOfficerPhone { get; set; }
        public string ParoleOfficerLocation { get; set; }
        public int StaffId { get; set; }
        public int ScreeningStatus { get; set; }
        public string OnSSI { get; set; }
        public string OnSSDI { get; set; }
        public string SpecialNeeds { get; set; }
        public string HealthComments { get; set; }
        public string PhyschologicalComments { get; set; }
        public string SupervisionPerformance { get; set; }
        public string ParoleBoardRecommendations { get; set; }
        public string UnitManagerComments { get; set; }
        public string Conduct { get; set; }
        public string CourtMandates { get; set; }
        public Nullable<System.DateTime> ScreeningDate { get; set; }
        public string ScreeningRecommendation { get; set; }
        public string ApprovalConditionComments { get; set; }
        public Nullable<int> DenialReason { get; set; }
        public string DenialComments { get; set; }
        public Nullable<System.DateTime> BedDate { get; set; }
        public string CurrentOffenseInfo { get; set; }
        public string OtherOffenseInfo { get; set; }
        public string OtherEmploymentEducationInfo { get; set; }
        public string OtherComments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DrugUseHistory { get; set; }
    
        public virtual ClientIdentifier ClientIdentifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningApprovalCondition> ClientScreeningApprovalConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningMedication> ClientScreeningMedications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningOffens> ClientScreeningOffenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningPreviousDenial> ClientScreeningPreviousDenials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningProgram> ClientScreeningPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningPsychCondition> ClientScreeningPsychConditions { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual ReferralSource ReferralSource { get; set; }
        public virtual User User { get; set; }
    }
}
