//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPrescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientPrescription()
        {
            this.ClientMedicationLogs = new HashSet<ClientMedicationLog>();
        }
    
        public int ClientPrescriptionId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> BinNumber { get; set; }
        public string PrescriptionNumber { get; set; }
        public int MedicationId { get; set; }
        public int PhysicianId { get; set; }
        public int MedicationType { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public decimal InitialQuantity { get; set; }
        public string NotForDispense { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMedicationLog> ClientMedicationLogs { get; set; }
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual MedicationBin MedicationBin { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Physician Physician { get; set; }
    }
}
