//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientIncidentReport
    {
        public int ClientIncidentReportId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int IncidentReportCodeId { get; set; }
        public int IncidentReportStatus { get; set; }
        public string Headline { get; set; }
        public string Description { get; set; }
        public int ReportingStaffId { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public Nullable<int> ServingStaffId { get; set; }
        public Nullable<System.DateTime> ServedDateTime { get; set; }
        public Nullable<int> Investigator { get; set; }
        public System.DateTime InvestigationDueDate { get; set; }
        public Nullable<int> RightsInformedStaffID { get; set; }
        public Nullable<System.DateTime> RightsInformedDateTime { get; set; }
        public string ResidentStatement { get; set; }
        public string AdditionalInfo { get; set; }
        public string RecommendedActions { get; set; }
        public string StaffRecommendations { get; set; }
        public System.DateTime ConclusionDueDate { get; set; }
        public Nullable<System.DateTime> ActualConclusionDate { get; set; }
        public string HearingOfficer { get; set; }
        public string Conclusion { get; set; }
        public string ResidentAppeal { get; set; }
        public Nullable<System.DateTime> AppealDate { get; set; }
        public string AppealHearingOfficer { get; set; }
        public string AppealDecision { get; set; }
        public string ResidentAppeal2 { get; set; }
        public Nullable<System.DateTime> AppealDate2 { get; set; }
        public string AppealHearingOfficer2 { get; set; }
        public string AppealDecision2 { get; set; }
        public Nullable<System.DateTime> FollowUpReviewDate { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual IncidentReportCode IncidentReportCode { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
