//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhysicalCharacteristic
    {
        public int ClientPhysicalCharacteristicsId { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> DNADate { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Build { get; set; }
        public Nullable<int> HairColor { get; set; }
        public Nullable<int> EyeColor { get; set; }
        public Nullable<int> Complexion { get; set; }
        public Nullable<int> Handed { get; set; }
        public string PhysicalRestrictions { get; set; }
        public string Allergies { get; set; }
        public string SpecialDiet { get; set; }
        public string ScarsTattoos { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        public virtual GlobalCode GlobalCode4 { get; set; }
    }
}
