//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSessionNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientSessionNote()
        {
            this.ClientSessionNoteCurriculums = new HashSet<ClientSessionNoteCurriculum>();
        }
    
        public int ClientSessionNoteId { get; set; }
        public int ClientGroupRegistrationId { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public int SessionLength { get; set; }
        public int Facilitator { get; set; }
        public int Attendance { get; set; }
        public Nullable<int> BAResult { get; set; }
        public Nullable<int> WeeklySelfHelps { get; set; }
        public string Behavior { get; set; }
        public string Assessment { get; set; }
        public string PlanText { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Progress { get; set; }
    
        public virtual ClientGroupRegistration ClientGroupRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSessionNoteCurriculum> ClientSessionNoteCurriculums { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual User User { get; set; }
    }
}
