//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOtherInfo
    {
        public int ClientOtherInfoId { get; set; }
        public int ClientId { get; set; }
        public string FemaleHeadOfHousehold { get; set; }
        public string HasChildrenAtHome { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string BirthCity { get; set; }
        public Nullable<int> BirthState { get; set; }
        public Nullable<int> MailBox { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual MailBox MailBox1 { get; set; }
    }
}
