//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCommunityFinancial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCommunityFinancial()
        {
            this.ClientCommunityFinancialDetails = new HashSet<ClientCommunityFinancialDetail>();
        }
    
        public int ClientCommunityFinancialsId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionTypeCFId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentLocationId { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
        public string Verified { get; set; }
        public Nullable<int> FeeType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal TransactionAmount { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCommunityFinancialDetail> ClientCommunityFinancialDetails { get; set; }
        public virtual Client Client { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual TransactionTypesCF TransactionTypesCF { get; set; }
    }
}
