//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAssessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAssessment()
        {
            this.ClientAssessmentFiles = new HashSet<ClientAssessmentFile>();
        }
    
        public int ClientAssessmentId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int AssessmentType { get; set; }
        public int AssessmentStatus { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<int> Length { get; set; }
        public string Score { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public Nullable<int> Evaluator { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string PreventLeaveOverlap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAssessmentFile> ClientAssessmentFiles { get; set; }
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
    }
}
