//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFederalIncidentReport
    {
        public int ClientFederalIncidentReportId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int IncidentReportStatus { get; set; }
        public int FederalIncidentReportCodeId { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public Nullable<System.DateTime> AwareDateTime { get; set; }
        public Nullable<System.DateTime> InvestigationDueDate { get; set; }
        public Nullable<System.DateTime> ConclusionDueDate { get; set; }
        public string IncidentPlace { get; set; }
        public string Description { get; set; }
        public int ReportingStaffId { get; set; }
        public byte[] ReportingStaffSignature { get; set; }
        public Nullable<System.DateTime> ReportingStaffSignatureDateTime { get; set; }
        public Nullable<int> ServingStaffId { get; set; }
        public Nullable<System.DateTime> ServedDateTime { get; set; }
        public string ResidentStatement { get; set; }
        public string AdditionalInfo { get; set; }
        public string InvestigatorComments { get; set; }
        public string ActionRecommended { get; set; }
        public Nullable<int> InvestigatorStaffId { get; set; }
        public byte[] InvestigatorSignature { get; set; }
        public Nullable<System.DateTime> InvestigatorSignatureDateTime { get; set; }
        public byte[] ResolutionStaffSignature { get; set; }
        public Nullable<System.DateTime> ResolutionStaffSignatureDateTime { get; set; }
        public byte[] ResolutionClientSignature { get; set; }
        public Nullable<System.DateTime> ResolutionClientSignatureDateTime { get; set; }
        public int IRFormality { get; set; }
        public Nullable<System.DateTime> ConclusionDate { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        public virtual FederalIncidentReportCode FederalIncidentReportCode { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
