//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProgramEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientProgramEnrollment()
        {
            this.ClientAssessments = new HashSet<ClientAssessment>();
            this.ClientCallCodes = new HashSet<ClientCallCode>();
            this.ClientCaseFiles = new HashSet<ClientCaseFile>();
            this.ClientCommunityFinancialDetails = new HashSet<ClientCommunityFinancialDetail>();
            this.ClientCommunityFinancialToDos = new HashSet<ClientCommunityFinancialToDo>();
            this.ClientContactNotes = new HashSet<ClientContactNote>();
            this.ClientFederalIncidentReports = new HashSet<ClientFederalIncidentReport>();
            this.ClientGroupRegistrations = new HashSet<ClientGroupRegistration>();
            this.ClientIncidentReports = new HashSet<ClientIncidentReport>();
            this.ClientMovements = new HashSet<ClientMovement>();
            this.ClientPositiveIncidents = new HashSet<ClientPositiveIncident>();
            this.ClientProgramConfinements = new HashSet<ClientProgramConfinement>();
            this.ClientProgramEnrollmentDockets = new HashSet<ClientProgramEnrollmentDocket>();
            this.ClientProgramFinancials = new HashSet<ClientProgramFinancial>();
            this.ClientProgramPhases = new HashSet<ClientProgramPhas>();
            this.ClientProgramPlacements = new HashSet<ClientProgramPlacement>();
            this.ClientProgramStatus = new HashSet<ClientProgramStatu>();
            this.ClientSecurityLevels = new HashSet<ClientSecurityLevel>();
            this.ClientSecurityProcedures = new HashSet<ClientSecurityProcedure>();
            this.ClientTreatmentPlans = new HashSet<ClientTreatmentPlan>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ClientProgramEnrollmentId { get; set; }
        public int ClientId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<int> ClientIdentifierId { get; set; }
        public Nullable<int> ClientScreeningId { get; set; }
        public int ManagingLocation { get; set; }
        public int ReferralSourceId { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public int CaseManagerId { get; set; }
        public Nullable<int> SecondaryCaseManagerId { get; set; }
        public Nullable<System.DateTime> ScheduledArrivalDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> HomeConfinementEligibleDate { get; set; }
        public Nullable<System.DateTime> TransitionalLivingDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> TerminationReason { get; set; }
        public Nullable<int> ReleaseTo { get; set; }
        public Nullable<int> SecondaryRelease { get; set; }
        public string DNARequired { get; set; }
        public Nullable<int> LabAccountNumber { get; set; }
        public Nullable<int> Billing { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<decimal> RecurringFee { get; set; }
        public Nullable<decimal> ProjectedFees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAssessment> ClientAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCallCode> ClientCallCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCaseFile> ClientCaseFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCommunityFinancialDetail> ClientCommunityFinancialDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCommunityFinancialToDo> ClientCommunityFinancialToDos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientContactNote> ClientContactNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFederalIncidentReport> ClientFederalIncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGroupRegistration> ClientGroupRegistrations { get; set; }
        public virtual ClientIdentifier ClientIdentifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientIncidentReport> ClientIncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPositiveIncident> ClientPositiveIncidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramConfinement> ClientProgramConfinements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollmentDocket> ClientProgramEnrollmentDockets { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientScreening ClientScreening { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        public virtual GlobalCode GlobalCode4 { get; set; }
        public virtual GlobalCode GlobalCode5 { get; set; }
        public virtual Program Program { get; set; }
        public virtual ReferralSource ReferralSource { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramFinancial> ClientProgramFinancials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramPhas> ClientProgramPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramPlacement> ClientProgramPlacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramStatu> ClientProgramStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSecurityLevel> ClientSecurityLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSecurityProcedure> ClientSecurityProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTreatmentPlan> ClientTreatmentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
