//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCommunityFinancialsQuickPay
    {
        public int QuickPayTransactionId { get; set; }
        public Nullable<int> ClientCommunityFinancialsId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int ProgramId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int PaymentTypeId { get; set; }
        public decimal TransactionAmount { get; set; }
        public int PaymentLocationId { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
        public string Comments { get; set; }
        public string Matched { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Verified { get; set; }
    
        public virtual PaymentLocation PaymentLocation { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Program Program { get; set; }
    }
}
