//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientGroupRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientGroupRegistration()
        {
            this.ClientSessionNotes = new HashSet<ClientSessionNote>();
        }
    
        public int ClientGroupRegistrationId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int TreatmentGroupId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int RegistrationStatus { get; set; }
        public Nullable<decimal> HoursRequired { get; set; }
        public Nullable<int> WeeklySelfHelpsRequired { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual TreatmentGroup TreatmentGroup { get; set; }
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSessionNote> ClientSessionNotes { get; set; }
    }
}
