//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLeaveSchedule
    {
        public int ClientLeaveScheduleId { get; set; }
        public int ClientLeaveId { get; set; }
        public int ScheduleType { get; set; }
        public int ScheduleDestinationKey { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MustPhoneCenter { get; set; }
        public string ReturnsToCenter { get; set; }
        public Nullable<int> InterimTransMode { get; set; }
        public string InterimTransDetails { get; set; }
        public Nullable<int> InterimTransDriver { get; set; }
        public Nullable<int> InterimTransVehicle { get; set; }
        public Nullable<int> InterimTravelTime { get; set; }
        public Nullable<System.DateTime> PhoneInTime { get; set; }
        public Nullable<int> PhoneInStaff { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientEmergencyContact ClientEmergencyContact { get; set; }
        public virtual ClientLeaf ClientLeaf { get; set; }
        public virtual ClientVehicle ClientVehicle { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual User User { get; set; }
    }
}
