//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientVehicle()
        {
            this.ClientEmergencyContacts = new HashSet<ClientEmergencyContact>();
            this.ClientLeaves = new HashSet<ClientLeaf>();
            this.ClientLeaves1 = new HashSet<ClientLeaf>();
            this.ClientLeaveSchedules = new HashSet<ClientLeaveSchedule>();
        }
    
        public int ClientVehicleId { get; set; }
        public int ClientId { get; set; }
        public int Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public Nullable<int> Color { get; set; }
        public int PlateState { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<System.DateTime> RegistrationExpiration { get; set; }
        public string InsuranceCarrier { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceExpiration { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEmergencyContact> ClientEmergencyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaf> ClientLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaf> ClientLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaveSchedule> ClientLeaveSchedules { get; set; }
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
    }
}
