//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLeaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientLeaf()
        {
            this.ClientLeaveSchedules = new HashSet<ClientLeaveSchedule>();
        }
    
        public int ClientLeaveId { get; set; }
        public int ClientId { get; set; }
        public int LeaveType { get; set; }
        public System.DateTime ScheduledDeparture { get; set; }
        public Nullable<System.DateTime> ActualDeparture { get; set; }
        public int DepartTransMode { get; set; }
        public string DepartTransDetails { get; set; }
        public Nullable<int> DepartTransDriver { get; set; }
        public Nullable<int> DepartTransVehicle { get; set; }
        public int DepartTravelTime { get; set; }
        public System.DateTime ScheduledReturn { get; set; }
        public Nullable<System.DateTime> ActualReturn { get; set; }
        public int ReturnTransMode { get; set; }
        public string ReturnTransDetails { get; set; }
        public Nullable<int> ReturnTransDriver { get; set; }
        public Nullable<int> ReturnTransVehicle { get; set; }
        public int ReturnTravelTime { get; set; }
        public string CannotOverride { get; set; }
        public string Comments { get; set; }
        public byte[] SignOutClientSignature { get; set; }
        public byte[] SignOutStaffSignature { get; set; }
        public byte[] SignInClientSignature { get; set; }
        public byte[] SignInStaffSignature { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string AuditComments { get; set; }
        public string SignOutUser { get; set; }
        public string SignInUser { get; set; }
    
        public virtual ClientEmergencyContact ClientEmergencyContact { get; set; }
        public virtual ClientEmergencyContact ClientEmergencyContact1 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientVehicle ClientVehicle { get; set; }
        public virtual ClientVehicle ClientVehicle1 { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaveSchedule> ClientLeaveSchedules { get; set; }
    }
}
