//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMovement
    {
        public int ClientMovementId { get; set; }
        public int ClientId { get; set; }
        public int MovementType { get; set; }
        public int MovementStatus { get; set; }
        public int TransportationMode { get; set; }
        public Nullable<int> ClientProgramEnrollmentId_Ending { get; set; }
        public Nullable<int> Program_Entering { get; set; }
        public Nullable<int> PointOfDeparture { get; set; }
        public Nullable<System.DateTime> EstimatedMovementDate { get; set; }
        public Nullable<System.DateTime> ActualMovementDate { get; set; }
        public string PropertyRemoved { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        public virtual Program Program { get; set; }
    }
}
