//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContactNote
    {
        public int ContactNoteId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientProgramEnrollmentId { get; set; }
        public int StaffId { get; set; }
        public int NoteType { get; set; }
        public Nullable<int> NoteTemplateId { get; set; }
        public System.DateTime NoteDateTime { get; set; }
        public Nullable<int> SessionLength { get; set; }
        public byte[] ClientSignature { get; set; }
        public byte[] StaffSignature { get; set; }
        public string DataText1 { get; set; }
        public string DataText2 { get; set; }
        public string DataText3 { get; set; }
        public string DataText4 { get; set; }
        public string DataText5 { get; set; }
        public string DataText6 { get; set; }
        public string DataText7 { get; set; }
        public string DataText8 { get; set; }
        public string DataText9 { get; set; }
        public string DataText10 { get; set; }
        public string DataText11 { get; set; }
        public string DataText12 { get; set; }
        public string DataText13 { get; set; }
        public string DataText14 { get; set; }
        public string DataText15 { get; set; }
        public string DataText16 { get; set; }
        public string DataText17 { get; set; }
        public string DataText18 { get; set; }
        public string DataText19 { get; set; }
        public string DataText20 { get; set; }
        public string Assessment { get; set; }
        public string PlanText { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DataLabel1 { get; set; }
        public string DataLabel2 { get; set; }
        public string DataLabel3 { get; set; }
        public string DataLabel4 { get; set; }
        public string DataLabel5 { get; set; }
        public string DataLabel6 { get; set; }
        public string DataLabel7 { get; set; }
        public string DataLabel8 { get; set; }
        public string DataLabel9 { get; set; }
        public string DataLabel10 { get; set; }
        public string DataLabel11 { get; set; }
        public string DataLabel12 { get; set; }
        public string DataLabel13 { get; set; }
        public string DataLabel14 { get; set; }
        public string DataLabel15 { get; set; }
        public string DataLabel16 { get; set; }
        public string DataLabel17 { get; set; }
        public string DataLabel18 { get; set; }
        public string DataLabel19 { get; set; }
        public string DataLabel20 { get; set; }
        public string ShowAssessmentPlan { get; set; }
    
        public virtual ClientProgramEnrollment ClientProgramEnrollment { get; set; }
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual User User { get; set; }
    }
}
