//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientResidentFinancialAccountDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientResidentFinancialAccountDetail()
        {
            this.CheckRegisters = new HashSet<CheckRegister>();
        }
    
        public int ClientResidentFinancialAccountDetailId { get; set; }
        public int ClientResidentFinancialAccountId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionTypeRFId { get; set; }
        public decimal TransactionAmount { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> PayPeriod { get; set; }
        public Nullable<System.DateTime> PayPeriodStartDate { get; set; }
        public Nullable<System.DateTime> PayPeriodEndDate { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<decimal> HoursWorked { get; set; }
        public Nullable<decimal> Tips { get; set; }
        public string Payee { get; set; }
        public string AdditionalPayeeInfo { get; set; }
        public string CheckMemo { get; set; }
        public string PrintCheck { get; set; }
        public string Emergency { get; set; }
        public string TransferFromAccountType { get; set; }
        public Nullable<int> TransferFromAccount { get; set; }
        public string TransferToAccountType { get; set; }
        public Nullable<int> TransferToAccount { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> IncomeSource { get; set; }
        public string CheckPrinted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRegister> CheckRegisters { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
    }
}
