//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFinancialAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyFinancialAccount()
        {
            this.CheckRegisters = new HashSet<CheckRegister>();
            this.CompanyFinancialAccounts1 = new HashSet<CompanyFinancialAccount>();
            this.CompanyFinancialAccounts11 = new HashSet<CompanyFinancialAccount>();
            this.CompanyFinancials = new HashSet<CompanyFinancial>();
            this.TransactionTypesRFs = new HashSet<TransactionTypesRF>();
        }
    
        public int CompanyFinancialAccountId { get; set; }
        public int CompanyId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> OffsetAccountId { get; set; }
        public Nullable<int> ParentAccountId { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRegister> CheckRegisters { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFinancialAccount> CompanyFinancialAccounts1 { get; set; }
        public virtual CompanyFinancialAccount CompanyFinancialAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFinancialAccount> CompanyFinancialAccounts11 { get; set; }
        public virtual CompanyFinancialAccount CompanyFinancialAccount2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFinancial> CompanyFinancials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTypesRF> TransactionTypesRFs { get; set; }
    }
}
