//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlobalCode()
        {
            this.AccountingPeriods = new HashSet<AccountingPeriod>();
            this.AccountingPeriods1 = new HashSet<AccountingPeriod>();
            this.CallCodes = new HashSet<CallCode>();
            this.ClientAddresses = new HashSet<ClientAddress>();
            this.ClientAddresses1 = new HashSet<ClientAddress>();
            this.ClientAlternateNames = new HashSet<ClientAlternateName>();
            this.ClientAlternateNames1 = new HashSet<ClientAlternateName>();
            this.ClientArrestInfoes = new HashSet<ClientArrestInfo>();
            this.ClientArrestInfoes1 = new HashSet<ClientArrestInfo>();
            this.ClientAssessments = new HashSet<ClientAssessment>();
            this.ClientAssessments1 = new HashSet<ClientAssessment>();
            this.ClientBikes = new HashSet<ClientBike>();
            this.ClientBondInfoes = new HashSet<ClientBondInfo>();
            this.ClientCallCodes = new HashSet<ClientCallCode>();
            this.ClientCaseFiles = new HashSet<ClientCaseFile>();
            this.ClientContactNotes = new HashSet<ClientContactNote>();
            this.ClientDiagnoses = new HashSet<ClientDiagnos>();
            this.ClientDockets = new HashSet<ClientDocket>();
            this.ClientDockets1 = new HashSet<ClientDocket>();
            this.ClientDockets2 = new HashSet<ClientDocket>();
            this.ClientDockets3 = new HashSet<ClientDocket>();
            this.ClientDrugsOfChoices = new HashSet<ClientDrugsOfChoice>();
            this.ClientDrugTreatments = new HashSet<ClientDrugTreatment>();
            this.ClientEducations = new HashSet<ClientEducation>();
            this.ClientEducations1 = new HashSet<ClientEducation>();
            this.ClientEmergencyContacts = new HashSet<ClientEmergencyContact>();
            this.ClientEmergencyContacts1 = new HashSet<ClientEmergencyContact>();
            this.ClientEmployments = new HashSet<ClientEmployment>();
            this.ClientEmploymentSkills = new HashSet<ClientEmploymentSkill>();
            this.ClientFederalIncidentReports = new HashSet<ClientFederalIncidentReport>();
            this.ClientFederalIncidentReports1 = new HashSet<ClientFederalIncidentReport>();
            this.ClientGroupRegistrations = new HashSet<ClientGroupRegistration>();
            this.ClientIncidentReports = new HashSet<ClientIncidentReport>();
            this.ClientJobHistories = new HashSet<ClientJobHistory>();
            this.ClientLeaves = new HashSet<ClientLeaf>();
            this.ClientLeaves1 = new HashSet<ClientLeaf>();
            this.ClientLeaves2 = new HashSet<ClientLeaf>();
            this.ClientLeaveSchedules = new HashSet<ClientLeaveSchedule>();
            this.ClientLeaveSchedules1 = new HashSet<ClientLeaveSchedule>();
            this.ClientMedicationLogs = new HashSet<ClientMedicationLog>();
            this.ClientMovements = new HashSet<ClientMovement>();
            this.ClientMovements1 = new HashSet<ClientMovement>();
            this.ClientMovements2 = new HashSet<ClientMovement>();
            this.ClientMovements3 = new HashSet<ClientMovement>();
            this.ClientOTCMedicationLogs = new HashSet<ClientOTCMedicationLog>();
            this.ClientOTCMedicationLogs1 = new HashSet<ClientOTCMedicationLog>();
            this.ClientOtherEmployments = new HashSet<ClientOtherEmployment>();
            this.ClientOtherInfoes = new HashSet<ClientOtherInfo>();
            this.ClientPassSites = new HashSet<ClientPassSite>();
            this.ClientPassSites1 = new HashSet<ClientPassSite>();
            this.ClientPhones = new HashSet<ClientPhone>();
            this.ClientPhotos = new HashSet<ClientPhoto>();
            this.ClientPhysicalCharacteristics = new HashSet<ClientPhysicalCharacteristic>();
            this.ClientPhysicalCharacteristics1 = new HashSet<ClientPhysicalCharacteristic>();
            this.ClientPhysicalCharacteristics2 = new HashSet<ClientPhysicalCharacteristic>();
            this.ClientPhysicalCharacteristics3 = new HashSet<ClientPhysicalCharacteristic>();
            this.ClientPhysicalCharacteristics4 = new HashSet<ClientPhysicalCharacteristic>();
            this.ClientPrescriptions = new HashSet<ClientPrescription>();
            this.ClientProgramEnrollments = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramEnrollments1 = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramEnrollments2 = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramEnrollments3 = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramEnrollments4 = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramEnrollments5 = new HashSet<ClientProgramEnrollment>();
            this.ClientProgramStatus = new HashSet<ClientProgramStatu>();
            this.ClientProgramStatus1 = new HashSet<ClientProgramStatu>();
            this.ClientResidentFinancialAccountDetails = new HashSet<ClientResidentFinancialAccountDetail>();
            this.ClientResidentFinancialAccounts = new HashSet<ClientResidentFinancialAccount>();
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
            this.Clients2 = new HashSet<Client>();
            this.Clients3 = new HashSet<Client>();
            this.Clients4 = new HashSet<Client>();
            this.ClientScreeningApprovalConditions = new HashSet<ClientScreeningApprovalCondition>();
            this.ClientScreeningMedications = new HashSet<ClientScreeningMedication>();
            this.ClientScreeningPreviousDenials = new HashSet<ClientScreeningPreviousDenial>();
            this.ClientScreeningPsychConditions = new HashSet<ClientScreeningPsychCondition>();
            this.ClientScreenings = new HashSet<ClientScreening>();
            this.ClientScreenings1 = new HashSet<ClientScreening>();
            this.ClientSecurityProcedures = new HashSet<ClientSecurityProcedure>();
            this.ClientSecurityProcedures1 = new HashSet<ClientSecurityProcedure>();
            this.ClientSessionNotes = new HashSet<ClientSessionNote>();
            this.ClientSessionNotes1 = new HashSet<ClientSessionNote>();
            this.ClientStatus = new HashSet<ClientStatu>();
            this.ClientTreatmentPlanGoals = new HashSet<ClientTreatmentPlanGoal>();
            this.ClientVehicles = new HashSet<ClientVehicle>();
            this.ClientVehicles1 = new HashSet<ClientVehicle>();
            this.ClientVehicles2 = new HashSet<ClientVehicle>();
            this.Companies = new HashSet<Company>();
            this.Companies1 = new HashSet<Company>();
            this.ContactNoteTemplates = new HashSet<ContactNoteTemplate>();
            this.CustomFields = new HashSet<CustomField>();
            this.Destinations = new HashSet<Destination>();
            this.Destinations1 = new HashSet<Destination>();
            this.EmailSubscriptions = new HashSet<EmailSubscription>();
            this.Employers = new HashSet<Employer>();
            this.FederalIncidentReportCodes = new HashSet<FederalIncidentReportCode>();
            this.RoleDocumentTypes = new HashSet<RoleDocumentType>();
            this.Headcounts = new HashSet<Headcount>();
            this.Headcounts1 = new HashSet<Headcount>();
            this.HeadcountDetails = new HashSet<HeadcountDetail>();
            this.IncidentReportCodes = new HashSet<IncidentReportCode>();
            this.MailBoxes = new HashSet<MailBox>();
            this.MedicationSubClasses = new HashSet<MedicationSubClass>();
            this.Offenses = new HashSet<Offens>();
            this.Offenses1 = new HashSet<Offens>();
            this.PaymentTypes = new HashSet<PaymentType>();
            this.PlacementSites = new HashSet<PlacementSite>();
            this.PlacementSites1 = new HashSet<PlacementSite>();
            this.PlacementSites2 = new HashSet<PlacementSite>();
            this.Programs = new HashSet<Program>();
            this.Programs1 = new HashSet<Program>();
            this.Programs2 = new HashSet<Program>();
            this.Programs3 = new HashSet<Program>();
            this.Programs4 = new HashSet<Program>();
            this.Programs5 = new HashSet<Program>();
            this.ReferralSources = new HashSet<ReferralSource>();
            this.ReferralSources1 = new HashSet<ReferralSource>();
            this.Reports = new HashSet<Report>();
            this.Reports1 = new HashSet<Report>();
            this.Reports2 = new HashSet<Report>();
            this.RoomBeds = new HashSet<RoomBed>();
            this.Rooms = new HashSet<Room>();
            this.RoomSearchSchedules = new HashSet<RoomSearchSchedule>();
            this.SecurityProcedureRequirements = new HashSet<SecurityProcedureRequirement>();
            this.ShiftNoteTypes = new HashSet<ShiftNoteType>();
            this.SpecialSecuritySetups = new HashSet<SpecialSecuritySetup>();
            this.SpecialSecuritySetups1 = new HashSet<SpecialSecuritySetup>();
            this.SpecialSecuritySetups2 = new HashSet<SpecialSecuritySetup>();
            this.SpecialSecuritySetups3 = new HashSet<SpecialSecuritySetup>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.TransactionCategoriesRFs = new HashSet<TransactionCategoriesRF>();
            this.TransactionCategoriesRFs1 = new HashSet<TransactionCategoriesRF>();
            this.TransactionTypes = new HashSet<TransactionType>();
            this.TransactionTypesCFs = new HashSet<TransactionTypesCF>();
            this.TransactionTypesRFs = new HashSet<TransactionTypesRF>();
            this.TreatmentGroupCurriculums = new HashSet<TreatmentGroupCurriculum>();
            this.VisitorLogs = new HashSet<VisitorLog>();
            this.Visitors = new HashSet<Visitor>();
            this.WordTemplates = new HashSet<WordTemplate>();
            this.WorkFlowEvents = new HashSet<WorkFlowEvent>();
        }
    
        public int GlobalCodeId { get; set; }
        public int CategoryId { get; set; }
        public string CodeName { get; set; }
        public string Description { get; set; }
        public string Active { get; set; }
        public string CannotModifyNameOrDelete { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingPeriod> AccountingPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingPeriod> AccountingPeriods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallCode> CallCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAddress> ClientAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAddress> ClientAddresses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAlternateName> ClientAlternateNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAlternateName> ClientAlternateNames1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientArrestInfo> ClientArrestInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientArrestInfo> ClientArrestInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAssessment> ClientAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAssessment> ClientAssessments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBike> ClientBikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBondInfo> ClientBondInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCallCode> ClientCallCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCaseFile> ClientCaseFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientContactNote> ClientContactNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDiagnos> ClientDiagnoses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDocket> ClientDockets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDocket> ClientDockets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDocket> ClientDockets2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDocket> ClientDockets3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDrugsOfChoice> ClientDrugsOfChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDrugTreatment> ClientDrugTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEducation> ClientEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEducation> ClientEducations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEmergencyContact> ClientEmergencyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEmergencyContact> ClientEmergencyContacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEmployment> ClientEmployments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEmploymentSkill> ClientEmploymentSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFederalIncidentReport> ClientFederalIncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFederalIncidentReport> ClientFederalIncidentReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGroupRegistration> ClientGroupRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientIncidentReport> ClientIncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientJobHistory> ClientJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaf> ClientLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaf> ClientLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaf> ClientLeaves2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaveSchedule> ClientLeaveSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeaveSchedule> ClientLeaveSchedules1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMedicationLog> ClientMedicationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOTCMedicationLog> ClientOTCMedicationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOTCMedicationLog> ClientOTCMedicationLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOtherEmployment> ClientOtherEmployments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOtherInfo> ClientOtherInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPassSite> ClientPassSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPassSite> ClientPassSites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhone> ClientPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhoto> ClientPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhysicalCharacteristic> ClientPhysicalCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhysicalCharacteristic> ClientPhysicalCharacteristics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhysicalCharacteristic> ClientPhysicalCharacteristics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhysicalCharacteristic> ClientPhysicalCharacteristics3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhysicalCharacteristic> ClientPhysicalCharacteristics4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPrescription> ClientPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramStatu> ClientProgramStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramStatu> ClientProgramStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientResidentFinancialAccountDetail> ClientResidentFinancialAccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientResidentFinancialAccount> ClientResidentFinancialAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningApprovalCondition> ClientScreeningApprovalConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningMedication> ClientScreeningMedications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningPreviousDenial> ClientScreeningPreviousDenials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningPsychCondition> ClientScreeningPsychConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreening> ClientScreenings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreening> ClientScreenings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSecurityProcedure> ClientSecurityProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSecurityProcedure> ClientSecurityProcedures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSessionNote> ClientSessionNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSessionNote> ClientSessionNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientStatu> ClientStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientTreatmentPlanGoal> ClientTreatmentPlanGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientVehicle> ClientVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientVehicle> ClientVehicles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientVehicle> ClientVehicles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactNoteTemplate> ContactNoteTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomField> CustomFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destination> Destinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destination> Destinations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSubscription> EmailSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employer> Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FederalIncidentReportCode> FederalIncidentReportCodes { get; set; }
        public virtual GlobalCodeCategory GlobalCodeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleDocumentType> RoleDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headcount> Headcounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headcount> Headcounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeadcountDetail> HeadcountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportCode> IncidentReportCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailBox> MailBoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationSubClass> MedicationSubClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offens> Offenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offens> Offenses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentType> PaymentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacementSite> PlacementSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacementSite> PlacementSites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacementSite> PlacementSites2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralSource> ReferralSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralSource> ReferralSources1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBed> RoomBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomSearchSchedule> RoomSearchSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityProcedureRequirement> SecurityProcedureRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftNoteType> ShiftNoteTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialSecuritySetup> SpecialSecuritySetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialSecuritySetup> SpecialSecuritySetups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialSecuritySetup> SpecialSecuritySetups2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialSecuritySetup> SpecialSecuritySetups3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCategoriesRF> TransactionCategoriesRFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCategoriesRF> TransactionCategoriesRFs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionType> TransactionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTypesCF> TransactionTypesCFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTypesRF> TransactionTypesRFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentGroupCurriculum> TreatmentGroupCurriculums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorLog> VisitorLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitor> Visitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordTemplate> WordTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlowEvent> WorkFlowEvents { get; set; }
    }
}
