//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadcountDetail
    {
        public int HeadcountDetailId { get; set; }
        public int HeadcountId { get; set; }
        public int ClientId { get; set; }
        public string ClientLastInitial { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int RoomId { get; set; }
        public string RoomBed { get; set; }
        public int ClientHeadcountStatus { get; set; }
        public Nullable<System.DateTime> ClientHeadcountTimestamp { get; set; }
        public string ClientHeadcountStaff { get; set; }
        public string Comments { get; set; }
        public string AdditionalCountText { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual Headcount Headcount { get; set; }
    }
}
