//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallInfo
    {
        public string CustomerName { get; set; }
        public string PhotoVirtualDirectory { get; set; }
        public string ApplicationURL { get; set; }
    }
}
