//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduleLog
    {
        public int JobScheduleLogId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastExecutionTime { get; set; }
        public Nullable<int> RecordsAffected { get; set; }
        public string StoredProcedure { get; set; }
        public string ErrorDescription { get; set; }
    }
}
