//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.ClientCommunityFinancialsQuickPays = new HashSet<ClientCommunityFinancialsQuickPay>();
            this.ClientMovements = new HashSet<ClientMovement>();
            this.ClientProgramEnrollments = new HashSet<ClientProgramEnrollment>();
            this.ClientScreeningPrograms = new HashSet<ClientScreeningProgram>();
            this.ContactNoteTemplates = new HashSet<ContactNoteTemplate>();
            this.FeeTypes = new HashSet<FeeType>();
            this.ProgramPhases = new HashSet<ProgramPhas>();
            this.TreatmentPlanTemplates = new HashSet<TreatmentPlanTemplate>();
            this.SecurityLevels = new HashSet<SecurityLevel>();
        }
    
        public int ProgramId { get; set; }
        public string Program1 { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ProgramType { get; set; }
        public int GovernanceAgency { get; set; }
        public string Residential { get; set; }
        public System.DateTime ProgramStart { get; set; }
        public Nullable<System.DateTime> ProgramEnd { get; set; }
        public Nullable<int> SecuritySchedulingType { get; set; }
        public Nullable<int> DefaultLength { get; set; }
        public Nullable<int> DefaultPhase { get; set; }
        public Nullable<int> DefaultSecurityLevel { get; set; }
        public Nullable<int> SignOutProcedure { get; set; }
        public Nullable<int> SignInProcedure { get; set; }
        public Nullable<int> DefaultGroupCompletionStatus { get; set; }
        public Nullable<int> AccountingType { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCommunityFinancialsQuickPay> ClientCommunityFinancialsQuickPays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMovement> ClientMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramEnrollment> ClientProgramEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScreeningProgram> ClientScreeningPrograms { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactNoteTemplate> ContactNoteTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeType> FeeTypes { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        public virtual GlobalCode GlobalCode4 { get; set; }
        public virtual GlobalCode GlobalCode5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPhas> ProgramPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentPlanTemplate> TreatmentPlanTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityLevel> SecurityLevels { get; set; }
    }
}
