//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSearchSchedule
    {
        public int RoomSearchScheduleId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public int ProcedureStatus { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
