//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftNote()
        {
            this.ShiftNoteClients = new HashSet<ShiftNoteClient>();
            this.ShiftNoteRelationships = new HashSet<ShiftNoteRelationship>();
            this.ShiftNoteRelationships1 = new HashSet<ShiftNoteRelationship>();
        }
    
        public int ShiftNoteId { get; set; }
        public System.DateTime ShiftNoteDate { get; set; }
        public int CompanyId { get; set; }
        public int ShiftNoteTypeId { get; set; }
        public string Note { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftNoteClient> ShiftNoteClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftNoteRelationship> ShiftNoteRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftNoteRelationship> ShiftNoteRelationships1 { get; set; }
        public virtual ShiftNoteType ShiftNoteType { get; set; }
    }
}
