//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialSecuritySetup
    {
        public int SpecialSecuritySetupId { get; set; }
        public int BuildingId { get; set; }
        public int CommonAreaSchedulingPeriod { get; set; }
        public int CommonAreaSchedulingFrequency { get; set; }
        public int ResidenceSchedulingPeriod { get; set; }
        public int ResidenceSchedulingFrequency { get; set; }
        public int InventorySchedulingPeriod { get; set; }
        public int InventorySchedulingFrequency { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
    }
}
