//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabSource
    {
        public string TabName { get; set; }
        public string OriginalTabSource { get; set; }
        public string TabSource1 { get; set; }
        public string DeleteSource { get; set; }
        public string AuditSource { get; set; }
    }
}
