//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCheckPreview
    {
        public int CompanyId { get; set; }
        public Nullable<int> ClientResidentFinancialAccountDetailId { get; set; }
        public Nullable<int> CompanyFinancialsId { get; set; }
        public int CheckNumber { get; set; }
        public System.DateTime CheckDate { get; set; }
        public decimal CheckAmount { get; set; }
        public string Payee { get; set; }
        public string AdditionalPayeeInfo { get; set; }
        public string CheckMemo { get; set; }
        public Nullable<int> CompanyFinancialAccountId { get; set; }
    }
}
