//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentGroupCalendar
    {
        public int TreatmentGroupCalendarId { get; set; }
        public int TreatmentGroupId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public int SessionLength { get; set; }
        public int Facilitator { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual TreatmentGroup TreatmentGroup { get; set; }
        public virtual User User { get; set; }
    }
}
