//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentPlanGoalTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreatmentPlanGoalTemplate()
        {
            this.TreatmentPlanActionTemplates = new HashSet<TreatmentPlanActionTemplate>();
        }
    
        public int TreatmentPlanGoalTemplateId { get; set; }
        public int TreatmentPlanTemplateId { get; set; }
        public string ProblemStatement { get; set; }
        public string Goal { get; set; }
        public int ProblemCategory { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentPlanActionTemplate> TreatmentPlanActionTemplates { get; set; }
        public virtual TreatmentPlanTemplate TreatmentPlanTemplate { get; set; }
    }
}
