//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentGroupCurriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreatmentGroupCurriculum()
        {
            this.ClientSessionNoteCurriculums = new HashSet<ClientSessionNoteCurriculum>();
        }
    
        public int TreatmentGroupCurriculumId { get; set; }
        public int TreatmentGroupId { get; set; }
        public string Curriculum { get; set; }
        public int CurriculumType { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSessionNoteCurriculum> ClientSessionNoteCurriculums { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual TreatmentGroup TreatmentGroup { get; set; }
    }
}
