//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreatmentGroup()
        {
            this.ClientGroupRegistrations = new HashSet<ClientGroupRegistration>();
            this.TreatmentGroupCalendars = new HashSet<TreatmentGroupCalendar>();
            this.TreatmentGroupCurriculums = new HashSet<TreatmentGroupCurriculum>();
        }
    
        public int TreatmentGroupId { get; set; }
        public string TreatmentGroup1 { get; set; }
        public int RoomId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int MeetingDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public int MeetingLength { get; set; }
        public int Facilitator { get; set; }
        public int Capacity { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGroupRegistration> ClientGroupRegistrations { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentGroupCalendar> TreatmentGroupCalendars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentGroupCurriculum> TreatmentGroupCurriculums { get; set; }
        public virtual User User { get; set; }
    }
}
