//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCallCodeSchedule
    {
        public int CallCodeScheduleId { get; set; }
        public int CallCodeId { get; set; }
        public string CallCode { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public System.DateTime ScheduleDate { get; set; }
    }
}
