//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientCaseFile
    {
        public int ClientCaseFileId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientProgramEnrollmentId { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string DocumentPath { get; set; }
        public string Description { get; set; }
    }
}
