//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientLeaf
    {
        public int ClientLeaveId { get; set; }
        public int ClientId { get; set; }
        public int LeaveTypeId { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime ScheduledDeparture { get; set; }
        public Nullable<System.DateTime> ActualDeparture { get; set; }
        public int DepartTransModeId { get; set; }
        public string DepartTransMode { get; set; }
        public string DepartTransDetails { get; set; }
        public Nullable<int> DepartTransDriverId { get; set; }
        public string DepartTransDriver { get; set; }
        public Nullable<int> DepartTransVehicleId { get; set; }
        public string DepartTransVehicle { get; set; }
        public int DepartTravelTime { get; set; }
        public System.DateTime ScheduledReturn { get; set; }
        public Nullable<System.DateTime> ActualReturn { get; set; }
        public int ReturnTransModeId { get; set; }
        public string ReturnTransMode { get; set; }
        public string ReturnTransDetails { get; set; }
        public Nullable<int> ReturnTransDriverId { get; set; }
        public string ReturnTransDriver { get; set; }
        public Nullable<int> ReturnTransVehicleId { get; set; }
        public string ReturnTransVehicle { get; set; }
        public int ReturnTravelTime { get; set; }
        public string CannotOverride { get; set; }
        public string Comments { get; set; }
        public byte[] SignOutClientSignature { get; set; }
        public byte[] SignOutStaffSignature { get; set; }
        public byte[] SignInClientSignature { get; set; }
        public byte[] SignInStaffSignature { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
