//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientEmployment
    {
        public int ClientEmploymentId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> WorkStatusId { get; set; }
        public string WorkStatus { get; set; }
        public string WorkWaiver { get; set; }
        public string Comments { get; set; }
    }
}
