//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientSecurityProcedure
    {
        public int ClientSecurityProcedureId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int SecurityProcedureTypeId { get; set; }
        public string SecurityProcedureType { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public int ProcedureStatusId { get; set; }
        public string ProcedureStatus { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string TrackingNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StaffId_AdministeredBy { get; set; }
        public string Staff_AdministeredBy { get; set; }
        public Nullable<int> StaffId_RecordedBy { get; set; }
        public string Staff_RecordedBy { get; set; }
        public byte[] ClientSignature { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
