//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientDrugsOfChoice
    {
        public int ClientDrugsOfChoiceId { get; set; }
        public int ClientId { get; set; }
        public int DrugId { get; set; }
        public string Drug { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
    }
}
