//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientPositiveIncident
    {
        public int ClientPositiveIncidentId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public int ReportingStaffId { get; set; }
        public string ReportingStaff { get; set; }
        public string IncidentDescription { get; set; }
    }
}
