//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientOtherInfo
    {
        public int ClientOtherInfoId { get; set; }
        public int ClientId { get; set; }
        public string FemaleHeadOfHousehold { get; set; }
        public string HasChildrenAtHome { get; set; }
        public Nullable<int> MailboxBuildingId { get; set; }
        public string MailboxBuilding { get; set; }
        public Nullable<int> MailboxId { get; set; }
        public string MailBox { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string BirthCity { get; set; }
        public Nullable<int> BirthStateId { get; set; }
        public string BirthState { get; set; }
    }
}
