//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientProgramEnrollmentDocket
    {
        public int ClientProgramEnrollmentDocketId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int ClientDocketId { get; set; }
        public string DocketNumber { get; set; }
        public Nullable<int> CourtId { get; set; }
        public string Court { get; set; }
        public string Attorney { get; set; }
        public string Judge { get; set; }
        public Nullable<int> CountyId { get; set; }
        public string County { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string District { get; set; }
        public Nullable<int> SentencedToId { get; set; }
        public string SentencedTo { get; set; }
        public string SentenceDescription { get; set; }
        public Nullable<int> TotalSentenceDays { get; set; }
        public Nullable<int> WorkReleaseDays { get; set; }
        public Nullable<int> DetentionDays { get; set; }
        public Nullable<int> HouseArrestDays { get; set; }
        public Nullable<int> MonitoringDays { get; set; }
        public Nullable<int> SupervisionDays { get; set; }
        public Nullable<int> CommunityServiceHours { get; set; }
        public Nullable<int> CreditedJailDays { get; set; }
        public Nullable<System.DateTime> DateSentenced { get; set; }
        public Nullable<System.DateTime> DateReceivedAtPrision { get; set; }
        public Nullable<System.DateTime> DateSentenceCommenced { get; set; }
        public Nullable<decimal> RestitutionAmount { get; set; }
        public string ProbationOfficer { get; set; }
        public string ProbationOfficerPhone { get; set; }
        public string VictimName { get; set; }
        public string VictimAddress { get; set; }
        public string SpecialConditions { get; set; }
        public string Offenses { get; set; }
        public string PrimaryDocket { get; set; }
        public string Active { get; set; }
    }
}
