//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientSessionNote
    {
        public int ClientSessionNoteId { get; set; }
        public int ClientGroupRegistrationId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int TreatmentGroupId { get; set; }
        public string TreatmentGroup { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public int SessionLength { get; set; }
        public int FacilitatorId { get; set; }
        public string Facilitator { get; set; }
        public int AttendanceId { get; set; }
        public string Attendance { get; set; }
        public Nullable<int> BAResultId { get; set; }
        public string BAResult { get; set; }
        public Nullable<int> WeeklySelfHelps { get; set; }
        public Nullable<int> WeeklySelfHelpsRequired { get; set; }
        public string Behavior { get; set; }
        public string Assessment { get; set; }
        public string Progress { get; set; }
        public string PlanText { get; set; }
        public string Curriculum { get; set; }
    }
}
