//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientFederalIncidentReport
    {
        public int ClientFederalIncidentReportId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int IncidentReportStatusId { get; set; }
        public string IncidentReportStatus { get; set; }
        public int FederalIncidentReportCodeId { get; set; }
        public string FederalIncidentReportCode { get; set; }
        public string FederalIRCodeDescription { get; set; }
        public int IncidentReportSeverityId { get; set; }
        public string IncidentReportSeverity { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public int IRFormalityId { get; set; }
        public string IRFormality { get; set; }
        public Nullable<System.DateTime> AwareDateTime { get; set; }
        public Nullable<System.DateTime> InvestigationDueDate { get; set; }
        public Nullable<System.DateTime> ConclusionDueDate { get; set; }
        public string IncidentPlace { get; set; }
        public string Description { get; set; }
        public int ReportingStaffId { get; set; }
        public string ReportingStaff { get; set; }
        public string ReportingStaffJobTitle { get; set; }
        public byte[] ReportingStaffSignature { get; set; }
        public Nullable<System.DateTime> ReportingStaffSignatureDateTime { get; set; }
        public Nullable<int> ServingStaffId { get; set; }
        public string ServingStaff { get; set; }
        public Nullable<System.DateTime> ServedDateTime { get; set; }
        public string ResidentStatement { get; set; }
        public string AdditionalInfo { get; set; }
        public string InvestigatorComments { get; set; }
        public string ActionRecommended { get; set; }
        public Nullable<int> InvestigatorStaffId { get; set; }
        public string Investigator { get; set; }
        public string InvestigatorJobTitle { get; set; }
        public byte[] InvestigatorSignature { get; set; }
        public Nullable<System.DateTime> InvestigatorSignatureDateTime { get; set; }
        public byte[] ResolutionStaffSignature { get; set; }
        public Nullable<System.DateTime> ResolutionStaffSignatureDateTime { get; set; }
        public byte[] ResolutionClientSignature { get; set; }
        public Nullable<System.DateTime> ResolutionClientSignatureDateTime { get; set; }
        public Nullable<System.DateTime> ConclusionDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
