//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientEducation
    {
        public int ClientEducationId { get; set; }
        public int ClientId { get; set; }
        public int EducationLevelId { get; set; }
        public string EducationLevel { get; set; }
        public int EducationStatusId { get; set; }
        public string EducationStatus { get; set; }
        public Nullable<int> CompletionYear { get; set; }
    }
}
