//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientGroupRegistration
    {
        public int ClientGroupRegistrationId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int TreatmentGroupId { get; set; }
        public string TreatmentGroup { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int RegistrationStatusId { get; set; }
        public string RegistrationStatus { get; set; }
        public Nullable<int> HoursRequired { get; set; }
        public Nullable<int> WeeklySelfHelpsRequired { get; set; }
        public int MeetingDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public string MeetingDayTime { get; set; }
        public int MeetingLength { get; set; }
        public string Facilitator { get; set; }
        public int RoomId { get; set; }
        public string Room { get; set; }
    }
}
