//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientBondInfo
    {
        public int ClientBondId { get; set; }
        public int ClientId { get; set; }
        public string BondName { get; set; }
        public string BondPhone { get; set; }
        public string BondAddress { get; set; }
        public string BondCity { get; set; }
        public Nullable<int> BondStateId { get; set; }
        public string BondState { get; set; }
        public string BondZIP { get; set; }
    }
}
