//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientPhysicalCharacteristic
    {
        public int ClientPhysicalCharacteristicsId { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> DNADate { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> BuildId { get; set; }
        public string Build { get; set; }
        public Nullable<int> HairColorId { get; set; }
        public string HairColor { get; set; }
        public Nullable<int> EyeColorId { get; set; }
        public string EyeColor { get; set; }
        public Nullable<int> ComplexionId { get; set; }
        public string Complexion { get; set; }
        public Nullable<int> HandedId { get; set; }
        public string Handed { get; set; }
        public string PhysicalRestrictions { get; set; }
        public string Allergies { get; set; }
        public string SpecialDiet { get; set; }
        public string ScarsTattoos { get; set; }
    }
}
