//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientProgramEnrollment
    {
        public int ClientProgramEnrollmentId { get; set; }
        public int ClientId { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public Nullable<int> ProgramTypeId { get; set; }
        public string ProgramType { get; set; }
        public int GovernanceAgencyId { get; set; }
        public string GovernanceAgency { get; set; }
        public string Residential { get; set; }
        public string IdentifierType { get; set; }
        public string Identifier { get; set; }
        public int ManagingLocationId { get; set; }
        public string ManagingLocation { get; set; }
        public int ReferralSourceId { get; set; }
        public string ReferralSource { get; set; }
        public string ReferralCode { get; set; }
        public string ReferralReportingGroup { get; set; }
        public string IncludeInCondensedReporting { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public int CaseManagerId { get; set; }
        public string CM_FirstName { get; set; }
        public string CM_LastName { get; set; }
        public string CM_Email { get; set; }
        public string CM_Phone { get; set; }
        public Nullable<int> SecondaryCaseManagerId { get; set; }
        public string CM2_FirstName { get; set; }
        public string CM2_LastName { get; set; }
        public string CM2_Email { get; set; }
        public string CM2_Phone { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> HomeConfinementEligibleDate { get; set; }
        public Nullable<System.DateTime> TransitionalLivingDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> TerminationReasonId { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<int> TerminationReasonSuccessFlagId { get; set; }
        public string TerminationReasonSuccessFlag { get; set; }
        public Nullable<int> ReleaseToId { get; set; }
        public string ReleaseTo { get; set; }
        public Nullable<int> SecondaryReleaseId { get; set; }
        public string SecondaryRelease { get; set; }
        public string DNARequired { get; set; }
        public Nullable<int> LabAccountNumberId { get; set; }
        public string LabAccountNumber { get; set; }
        public Nullable<int> BillingId { get; set; }
        public string Billing { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ScheduledArrivalDate { get; set; }
        public Nullable<decimal> RecurringFee { get; set; }
        public Nullable<decimal> ProjectedFees { get; set; }
    }
}
