//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientJobHistory
    {
        public int ClientJobHistoryId { get; set; }
        public int ClientId { get; set; }
        public int EmployerId { get; set; }
        public string Employer { get; set; }
        public string ContactName { get; set; }
        public string SecondaryContactName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZIP { get; set; }
        public string PhoneNumber { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string ApprovedEmployer { get; set; }
        public string WorkersCompNumber { get; set; }
        public string Comments { get; set; }
        public string State { get; set; }
        public Nullable<int> WorkTypeId { get; set; }
        public string WorkType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EmploymentConfirmationDate { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public string Tips { get; set; }
        public string Commission { get; set; }
        public string PieceWork { get; set; }
    }
}
