//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientScreeningApprovalCondition
    {
        public int ClientScreeningApprovalConditionId { get; set; }
        public int ClientScreeningId { get; set; }
        public string ApprovalCondition { get; set; }
    }
}
