//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientArrestInfo
    {
        public int ClientArrestInfoId { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> ParoleEligibleDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<int> PriorFailureToAppearId { get; set; }
        public string PriorFailureToAppear { get; set; }
        public string NoContactOrders { get; set; }
        public string ParoleBoardNote { get; set; }
        public Nullable<System.DateTime> ParoleBoardDate { get; set; }
        public Nullable<int> ParoleEligibilityId { get; set; }
        public string ParoleEligibility { get; set; }
        public string ParoleEligibleNote { get; set; }
        public Nullable<System.DateTime> DischargeToSS { get; set; }
    }
}
