//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientVehicle
    {
        public int ClientVehicleId { get; set; }
        public int ClientId { get; set; }
        public int MakeId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int ColorId { get; set; }
        public string Color { get; set; }
        public int PlateStateId { get; set; }
        public string PlateState { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<System.DateTime> RegistrationExpiration { get; set; }
        public string InsuranceCarrier { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceExpiration { get; set; }
    }
}
