//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientLeaveSchedule
    {
        public int ClientLeaveScheduleId { get; set; }
        public int ClientLeaveId { get; set; }
        public int ScheduleTypeId { get; set; }
        public string ScheduleType { get; set; }
        public string ScheduleDestination { get; set; }
        public string ScheduleDestinationPhone { get; set; }
        public string ScheduleDestinationAddress { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MustPhoneCenter { get; set; }
        public Nullable<System.DateTime> PhoneInTime { get; set; }
        public Nullable<int> PhoneInStaff { get; set; }
        public string ReturnsToCenter { get; set; }
        public Nullable<int> InterimTransModeId { get; set; }
        public string InterimTransMode { get; set; }
        public string InterimTransDetails { get; set; }
        public Nullable<int> InterimTransDriverId { get; set; }
        public string InterimTransDriver { get; set; }
        public Nullable<int> InterimTransVehicleId { get; set; }
        public string InterimTransVehicle { get; set; }
        public Nullable<int> InterimTravelTime { get; set; }
        public string Comments { get; set; }
    }
}
