//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientOffens
    {
        public int ClientOffenseId { get; set; }
        public int ClientId { get; set; }
        public int OffenseId { get; set; }
        public string Offense { get; set; }
        public Nullable<int> JurisdictionId { get; set; }
        public string Jurisdiction { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> OffenseDate { get; set; }
        public Nullable<int> DocketId { get; set; }
        public string DocketNumber { get; set; }
        public string RevocationStatus { get; set; }
        public string Comments { get; set; }
    }
}
