//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientOtherEmployment
    {
        public int ClientOtherEmploymentId { get; set; }
        public int ClientId { get; set; }
        public string Employer { get; set; }
        public string ContactName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string PhoneNumber { get; set; }
        public string Comments { get; set; }
    }
}
