//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientCommunityFinancialDetail
    {
        public int ClientCommunityFinancialDetailId { get; set; }
        public int ClientCommunityFinancialsId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int ClientId { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int ManagingLocationId { get; set; }
        public string ManagingLocation { get; set; }
        public int ReferralSourceId { get; set; }
        public string ReferralSource { get; set; }
        public decimal LineItemAmount { get; set; }
        public string LineItemComments { get; set; }
        public string AccountNumber { get; set; }
    }
}
