//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientPrescription
    {
        public int ClientPrescriptionId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> BinNumberId { get; set; }
        public string BinNumber { get; set; }
        public string PrescriptionNumber { get; set; }
        public int MedicationId { get; set; }
        public string MedicationName { get; set; }
        public int MedicationClassId { get; set; }
        public string MedicationClass { get; set; }
        public int MedicationSubClassId { get; set; }
        public string MedicationSubclass { get; set; }
        public int PhysicianId { get; set; }
        public string PhysicianName { get; set; }
        public string PhoneNumber { get; set; }
        public int MedicationTypeId { get; set; }
        public string MedicationType { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public decimal InitialQuantity { get; set; }
        public string NotForDispense { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
    }
}
