//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientAssessment
    {
        public int ClientAssessmentId { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int AssessmentTypeId { get; set; }
        public string AssessmentType { get; set; }
        public int AssessmentStatusId { get; set; }
        public string AssessmentStatus { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<int> EvaluatorId { get; set; }
        public string Evaluator { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<int> Length { get; set; }
        public string Score { get; set; }
        public string Comments { get; set; }
    }
}
