//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientIncidentReport
    {
        public int ClientIncidentReportId { get; set; }
        public int ClientId { get; set; }
        public int ClientProgramEnrollmentId { get; set; }
        public int IncidentReportCodeId { get; set; }
        public string IncidentReportCode { get; set; }
        public string Description { get; set; }
        public int IncidentReportSeverityId { get; set; }
        public string IncidentReportSeverity { get; set; }
        public int IncidentReportStatusId { get; set; }
        public string IncidentReportStatus { get; set; }
        public string Headline { get; set; }
        public string Summary { get; set; }
        public int ReportingStaffId { get; set; }
        public string ReportingStaff { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public Nullable<int> ServingStaffId { get; set; }
        public string ServingStaff { get; set; }
        public Nullable<System.DateTime> ServedDateTime { get; set; }
        public Nullable<int> InvestigatorId { get; set; }
        public string Investigator { get; set; }
        public System.DateTime InvestigationDueDate { get; set; }
        public Nullable<int> RightsInformedStaffID { get; set; }
        public string RightsInformedStaff { get; set; }
        public Nullable<System.DateTime> RightsInformedDateTime { get; set; }
        public string ResidentStatement { get; set; }
        public string AdditionalInfo { get; set; }
        public string RecommendedActions { get; set; }
        public string StaffRecommendations { get; set; }
        public string HearingOfficer { get; set; }
        public System.DateTime ConclusionDueDate { get; set; }
        public Nullable<System.DateTime> ActualConclusionDate { get; set; }
        public string Conclusion { get; set; }
        public string ResidentAppeal { get; set; }
        public string AppealDecision { get; set; }
        public Nullable<System.DateTime> FollowUpReviewDate { get; set; }
        public string ResidentAppeal2 { get; set; }
        public string AppealDecision2 { get; set; }
        public Nullable<System.DateTime> AppealDate { get; set; }
        public string AppealHearingOfficer { get; set; }
        public Nullable<System.DateTime> AppealDate2 { get; set; }
        public string AppealHearingOfficer2 { get; set; }
    }
}
