//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientTreatmentPlanGoal
    {
        public int ClientTreatmentPlanGoalId { get; set; }
        public int ClientTreatmentPlanId { get; set; }
        public string ProblemStatement { get; set; }
        public string Goal { get; set; }
        public int ProblemCategoryId { get; set; }
        public string ProblemCategory { get; set; }
        public string Comments { get; set; }
    }
}
