//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientMovement
    {
        public int ClientMovementId { get; set; }
        public int ClientId { get; set; }
        public int MovementTypeId { get; set; }
        public string MovementType { get; set; }
        public int MovementStatusId { get; set; }
        public string MovementStatus { get; set; }
        public int TransportationModeId { get; set; }
        public string TransportationMode { get; set; }
        public Nullable<int> ClientProgramEnrollmentId_Ending { get; set; }
        public Nullable<int> Program_EnteringId { get; set; }
        public string Program_Entering { get; set; }
        public Nullable<int> PointOfDepartureId { get; set; }
        public string PointOfDeparture { get; set; }
        public Nullable<int> Program_LeavingId { get; set; }
        public string Program_Leaving { get; set; }
        public Nullable<System.DateTime> EstimatedMovementDate { get; set; }
        public Nullable<System.DateTime> ActualMovementDate { get; set; }
        public string PropertyRemoved { get; set; }
        public string Comments { get; set; }
    }
}
