//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientRoom
    {
        public int ClientRoomId { get; set; }
        public int ClientId { get; set; }
        public int RoomBedId { get; set; }
        public int BuildingId { get; set; }
        public string Building { get; set; }
        public int RoomId { get; set; }
        public string Room { get; set; }
        public int BedId { get; set; }
        public string Bed { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CurrentlyAssigned { get; set; }
    }
}
