//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientDrugTreatment
    {
        public int ClientDrugTreatmentId { get; set; }
        public int ClientId { get; set; }
        public int ExternalFacilityId { get; set; }
        public string ExternalFacility { get; set; }
        public Nullable<int> Year { get; set; }
        public string Comments { get; set; }
    }
}
