//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientScreening
    {
        public int ClientScreeningId { get; set; }
        public int ClientId { get; set; }
        public string IdentifierType { get; set; }
        public string Identifier { get; set; }
        public System.DateTime ScreeningFileReceivedDate { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string ParoleOfficer { get; set; }
        public string ParoleOfficerPhone { get; set; }
        public string ParoleOfficerLocation { get; set; }
        public string Screener { get; set; }
        public int ScreeningStatusId { get; set; }
        public string ScreeningStatus { get; set; }
        public string OnSSI { get; set; }
        public string OnSSDI { get; set; }
        public string SpecialNeeds { get; set; }
        public string HealthComments { get; set; }
        public string PhyschologicalComments { get; set; }
        public string SupervisionPerformance { get; set; }
        public string ParoleBoardRecommendations { get; set; }
        public string UnitManagerComments { get; set; }
        public string Conduct { get; set; }
        public string CourtMandates { get; set; }
        public Nullable<System.DateTime> ScreeningDate { get; set; }
        public string ScreeningRecommendation { get; set; }
        public string ApprovalConditionComments { get; set; }
        public string DenialReason { get; set; }
        public string DenialComments { get; set; }
        public Nullable<System.DateTime> BedDate { get; set; }
        public string ReferralSource { get; set; }
        public string OtherOffenseInfo { get; set; }
        public string OtherEmploymentEducationInfo { get; set; }
        public string OtherComments { get; set; }
    }
}
