//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientDiagnos
    {
        public int ClientDiagnosisId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> DiagnosisId { get; set; }
        public string DiagnosisCode { get; set; }
        public string Diagnosis { get; set; }
        public string Active { get; set; }
    }
}
