//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGlobalCode
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string AllowAddDelete { get; set; }
        public int GlobalCodeId { get; set; }
        public string CodeName { get; set; }
        public string Description { get; set; }
        public string CannotModifyNameOrDelete { get; set; }
        public string Active { get; set; }
    }
}
