//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public int VisitId { get; set; }
        public int CompanyId { get; set; }
        public int VisitType { get; set; }
        public int VisitorKey { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string VisitDescription { get; set; }
        public System.DateTime DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public string SignedInBy { get; set; }
        public string SignedOutBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public byte[] SignOutStaffSignature { get; set; }
        public byte[] SignInStaffSignature { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
    }
}
