//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSecurityProcedureRequirement
    {
        public int SecurityProcedureRequirementId { get; set; }
        public int SecurityLevelId { get; set; }
        public int SecurityLevel { get; set; }
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public int SecurityProcedureTypeId { get; set; }
        public string SecurityProcedureType { get; set; }
        public int Frequency { get; set; }
    }
}
