//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vShiftNote
    {
        public int ShiftNoteId { get; set; }
        public System.DateTime ShiftNoteDate { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public int ShiftNoteTypeId { get; set; }
        public string ShiftNoteType { get; set; }
        public string Priority { get; set; }
        public string Note { get; set; }
        public string Clients { get; set; }
        public string RelatedShiftNotes { get; set; }
        public string CreatedBy_UserId { get; set; }
        public string CreatedBy_Name { get; set; }
    }
}
