//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTask
    {
        public int TaskId { get; set; }
        public int TaskTypeId { get; set; }
        public string TaskType { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ClientProgramEnrollmentId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string StaffAssignee { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupAssignee { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Comments { get; set; }
        public string Active { get; set; }
    }
}
