//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseMangement.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowStepAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkFlowStepAction()
        {
            this.QueueStepActions = new HashSet<QueueStepAction>();
        }
    
        public int WorkFlowStepActionId { get; set; }
        public Nullable<int> WorkFlowStepId { get; set; }
        public Nullable<int> WorkFlowActionId { get; set; }
        public Nullable<int> CreationOffsetDays { get; set; }
        public Nullable<int> WorkFlowEventOffSetFieldId { get; set; }
        public Nullable<int> ExecutionOffsetDays { get; set; }
        public string ColumnVarchar1 { get; set; }
        public string ColumnVarchar2 { get; set; }
        public string ColumnVarchar3 { get; set; }
        public string ColumnVarchar4 { get; set; }
        public string ColumnVarchar5 { get; set; }
        public string ColumnVarchar6 { get; set; }
        public string ColumnVarchar7 { get; set; }
        public string ColumnVarchar8 { get; set; }
        public string ColumnVarchar9 { get; set; }
        public string ColumnVarchar10 { get; set; }
        public string ColumnVarchar11 { get; set; }
        public string ColumnVarchar12 { get; set; }
        public string ColumnVarchar13 { get; set; }
        public string ColumnVarchar14 { get; set; }
        public string ColumnVarchar15 { get; set; }
        public string ColumnVarchar16 { get; set; }
        public string ColumnVarchar17 { get; set; }
        public string ColumnVarchar18 { get; set; }
        public string ColumnVarchar19 { get; set; }
        public string ColumnVarchar20 { get; set; }
        public string ColumnText1 { get; set; }
        public string ColumnText2 { get; set; }
        public string ColumnText3 { get; set; }
        public string ColumnText4 { get; set; }
        public string ColumnText5 { get; set; }
        public string ColumnText6 { get; set; }
        public string ColumnText7 { get; set; }
        public string ColumnText8 { get; set; }
        public string ColumnText9 { get; set; }
        public string ColumnText10 { get; set; }
        public Nullable<int> ColumnInteger1 { get; set; }
        public Nullable<int> ColumnInteger2 { get; set; }
        public Nullable<int> ColumnInteger3 { get; set; }
        public Nullable<int> ColumnInteger4 { get; set; }
        public Nullable<int> ColumnInteger5 { get; set; }
        public Nullable<int> ColumnInteger6 { get; set; }
        public Nullable<int> ColumnInteger7 { get; set; }
        public Nullable<int> ColumnInteger8 { get; set; }
        public Nullable<int> ColumnInteger9 { get; set; }
        public Nullable<int> ColumnInteger10 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime1 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime2 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime3 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime4 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime5 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime6 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime7 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime8 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime9 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime10 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime11 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime12 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime13 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime14 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime15 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime16 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime17 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime18 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime19 { get; set; }
        public Nullable<System.DateTime> ColumnDatetime20 { get; set; }
        public Nullable<int> ColumnGlobalCode1 { get; set; }
        public Nullable<int> ColumnGlobalCode2 { get; set; }
        public Nullable<int> ColumnGlobalCode3 { get; set; }
        public Nullable<int> ColumnGlobalCode4 { get; set; }
        public Nullable<int> ColumnGlobalCode5 { get; set; }
        public Nullable<int> ColumnGlobalCode6 { get; set; }
        public Nullable<int> ColumnGlobalCode7 { get; set; }
        public Nullable<int> ColumnGlobalCode8 { get; set; }
        public Nullable<int> ColumnGlobalCode9 { get; set; }
        public Nullable<int> ColumnGlobalCode10 { get; set; }
        public Nullable<int> ColumnGlobalCode11 { get; set; }
        public Nullable<int> ColumnGlobalCode12 { get; set; }
        public Nullable<int> ColumnGlobalCode13 { get; set; }
        public Nullable<int> ColumnGlobalCode14 { get; set; }
        public Nullable<int> ColumnGlobalCode15 { get; set; }
        public Nullable<int> ColumnGlobalCode16 { get; set; }
        public Nullable<int> ColumnGlobalCode17 { get; set; }
        public Nullable<int> ColumnGlobalCode18 { get; set; }
        public Nullable<int> ColumnGlobalCode19 { get; set; }
        public Nullable<int> ColumnGlobalCode20 { get; set; }
        public Nullable<decimal> ColumnMoney1 { get; set; }
        public Nullable<decimal> ColumnMoney2 { get; set; }
        public Nullable<decimal> ColumnMoney3 { get; set; }
        public Nullable<decimal> ColumnMoney4 { get; set; }
        public Nullable<decimal> ColumnMoney5 { get; set; }
        public Nullable<decimal> ColumnMoney6 { get; set; }
        public Nullable<decimal> ColumnMoney7 { get; set; }
        public Nullable<decimal> ColumnMoney8 { get; set; }
        public Nullable<decimal> ColumnMoney9 { get; set; }
        public Nullable<decimal> ColumnMoney10 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueStepAction> QueueStepActions { get; set; }
        public virtual WorkFlowAction WorkFlowAction { get; set; }
        public virtual WorkflowEventOffsetField WorkflowEventOffsetField { get; set; }
        public virtual WorkflowStep WorkflowStep { get; set; }
    }
}
